version: "3.9"  # optional since v1.27.0
services:
  redis:
    ports:
      - 127.0.0.1:6379:6379
    image: redis

  web:
    ports:
     - 8080:80
    volumes:
     - ./frontend:/usr/share/nginx/html:ro
    image: nginx

  ss_position:
    build: backend/SS_Position/.
    ports:
      - 8081:8081
    links:
      - redis
      - ss_maploader
  
  ss_maploader:
    build: backend/SS_MapLoader/.
    ports:
      - 8082:8082

  ss_connector:
    build: backend/SS_Connector/.
    ports:
      - 8083:8083
      - 8084:8084
  
  ss_itemskeeper:
    build: backend/SS_ItemsKeeper/.
    ports:
      - 8085:8085